---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-${MOLECULE_DISTRO:-debian12}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    pre_build_image: true
    #
    # Needs to be privileged so that we can unmount
    # /etc/resolv.conf and then modify it.
    #
    privileged: true
